pipeline:
  agent: any

  stages:
    - stage: "Build"
      steps:
        - sh: |
            echo "Building the app..."
            mkdir -p build
            echo "sample artifact" > build/app.txt

    - stage: "Test"
      steps:
        - sh: |
            echo "Running tests..."
            echo '<?xml version="1.0" encoding="UTF-8"?>' > test-results.xml
            echo '<testsuites><testsuite name="demo" tests="1" failures="0"><testcase classname="demo" name="sample-test"/></testsuite></testsuites>' >> test-results.xml
        - junit:
            testResults: "test-results.xml"

    - stage: "Deploy"
      when:
        branch: "main"
      steps:
        - sh: echo "Deploying app to staging..."
