pipeline:
  agent: any

  stages:
    - stage: "Build"
      steps:
        - sh: echo "Building the app..."

    - stage: "Test"
      steps:
        - sh: echo "Running tests..."
        - sh: echo '<testsuite tests="1"></testsuite>' > test-results.xml
        - junit: "test-results.xml"

    - stage: "Deploy"
      when:
        branch: "main"
      steps:
        - sh: echo "Deploying app to staging..."
